apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  config.yaml: |
    access:
      repo_plugins:
        zengchen1024/repo-test:
        - label
        - lifecycle
        - welcome
        - assign-issue
        - opengauss-review

        opengauss:
        - label
        - lifecycle
        - welcome
        - assign-issue
        - opengauss-review

        openlookeng/community:
        - sweepstakes

        zengchen1024/openeuler-test:
        - openeuler-lifecycle

      plugins:
      - name: lifecycle
        endpoint: http://service-lifecycle.robot-gitee-opengauss.svc.cluster.local:8888/gitee-hook
        events:
        - "Note Hook"
      - name: welcome
        endpoint: http://service-welcome.robot-gitee-opengauss.svc.cluster.local:8888/gitee-hook
        events:
        - "Issue Hook"
        - "Merge Request Hook"
      - name: label
        endpoint: http://service-label.robot-gitee-opengauss.svc.cluster.local:8888/gitee-hook
        events:
        - "Merge Request Hook"
        - "Note Hook"
      - name: assign-issue
        endpoint: http://service-assign-issue.robot-gitee-opengauss.svc.cluster.local:8888/gitee-hook
        events:
        - "Note Hook"
      - name: opengauss-review
        endpoint: http://service-opengauss-review.robot-gitee-opengauss.svc.cluster.local:8888/gitee-hook
        events:
        - "Merge Request Hook"
        - "Note Hook"
      - name: sweepstakes
        endpoint: http://service-sweepstakes.robot-gitee-openlookeng.svc.cluster.local:8888/gitee-hook
        events:
        - "Note Hook"
      - name: openeuler-lifecycle
        endpoint: http://service-lifecycle.robot-gitee-openeuler.svc.cluster.local:8888/gitee-hook
        events:
        - "Note Hook"
      - name: robot-gitee-openeuler-assign-issue
        endpoint: http://service-assign-issue.robot-gitee-openeuler.svc.cluster.local:8888/gitee-hook
        events:
        - "Note Hook"
