apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  config.yaml: |
    access:
      repo_plugins:
        zengchen1024/repo-test:
        - label
        - lifecycle
        - welcome
        - assign-issue
        - opengauss-review

        opengauss:
        - label
        - lifecycle
        - welcome
        - assign-issue
        - opengauss-review

        openlookeng/community:
        - sweepstakes

        ci-bot:
        - robot-gitee-openeuler-label
        - robot-gitee-openeuler-lifecycle 
        - robot-gitee-openeuler-assign-issue
        - robot-gitee-openeuler-openeuler-review
        - robot-gitee-openeuler-openeuler-welcome
        
        openeuler:
        - robot-gitee-openeuler-label
        - robot-gitee-openeuler-lifecycle 
        - robot-gitee-openeuler-assign-issue
        - robot-gitee-openeuler-openeuler-review
        - robot-gitee-openeuler-openeuler-welcome
        
        src-openeuler:
        - robot-gitee-openeuler-label
        - robot-gitee-openeuler-lifecycle 
        - robot-gitee-openeuler-assign-issue
        - robot-gitee-openeuler-openeuler-review
        - robot-gitee-openeuler-openeuler-welcome
        
        openeuler-competition:
        - robot-gitee-openeuler-label
        - robot-gitee-openeuler-lifecycle 
        - robot-gitee-openeuler-assign-issue
        - robot-gitee-openeuler-openeuler-review
        - robot-gitee-openeuler-openeuler-welcome
        
        openeuler-compliance:
        - robot-gitee-openeuler-label
        - robot-gitee-openeuler-lifecycle 
        - robot-gitee-openeuler-assign-issue
        - robot-gitee-openeuler-openeuler-review
        - robot-gitee-openeuler-openeuler-welcome
        
        openeuler-risc-v:
        - robot-gitee-openeuler-label
        - robot-gitee-openeuler-lifecycle 
        - robot-gitee-openeuler-assign-issue
        - robot-gitee-openeuler-openeuler-review
        - robot-gitee-openeuler-openeuler-welcome
        
        openeuler-practice-courses:
        - robot-gitee-openeuler-label
        - robot-gitee-openeuler-lifecycle 
        - robot-gitee-openeuler-assign-issue
        - robot-gitee-openeuler-openeuler-review
        - robot-gitee-openeuler-openeuler-welcome
        
        openeuler-customization:
        - robot-gitee-openeuler-label
        - robot-gitee-openeuler-lifecycle 
        - robot-gitee-openeuler-assign-issue
        - robot-gitee-openeuler-openeuler-review
        - robot-gitee-openeuler-openeuler-welcome

      plugins:
      - name: lifecycle
        endpoint: http://service-lifecycle.robot-gitee-opengauss.svc.cluster.local:8888/gitee-hook
        events:
        - "Note Hook"
      - name: welcome
        endpoint: http://service-welcome.robot-gitee-opengauss.svc.cluster.local:8888/gitee-hook
        events:
        - "Issue Hook"
        - "Merge Request Hook"
      - name: label
        endpoint: http://service-label.robot-gitee-opengauss.svc.cluster.local:8888/gitee-hook
        events:
        - "Merge Request Hook"
        - "Note Hook"
      - name: assign-issue
        endpoint: http://service-assign-issue.robot-gitee-opengauss.svc.cluster.local:8888/gitee-hook
        events:
        - "Note Hook"
      - name: opengauss-review
        endpoint: http://service-opengauss-review.robot-gitee-opengauss.svc.cluster.local:8888/gitee-hook
        events:
        - "Merge Request Hook"
        - "Note Hook"
      - name: sweepstakes
        endpoint: http://service-sweepstakes.robot-gitee-openlookeng.svc.cluster.local:8888/gitee-hook
        events:
        - "Note Hook"
      - name: robot-gitee-openeuler-lifecycle
        endpoint: http://service-lifecycle.robot-gitee-openeuler.svc.cluster.local:8888/gitee-hook
        events:
        - "Note Hook"
      - name: robot-gitee-openeuler-assign-issue
        endpoint: http://service-assign-issue.robot-gitee-openeuler.svc.cluster.local:8888/gitee-hook
        events:
        - "Note Hook"
      - name: robot-gitee-openeuler-label
        endpoint: http://service-label.robot-gitee-openeuler.svc.cluster.local:8888/gitee-hook
        events:
        - "Merge Request Hook"
        - "Note Hook"
      - name: robot-gitee-openeuler-openeuler-welcome
        endpoint: http://service-openeuler-welcome.robot-gitee-openeuler.svc.cluster.local:8888/gitee-hook
        events:
        - "Issue Hook"
        - "Merge Request Hook"
      - name: robot-gitee-openeuler-openeuler-review
        endpoint: http://service-openeuler-review.robot-gitee-openeuler.svc.cluster.local:8888/gitee-hook
        events:
        - "Merge Request Hook"
        - "Note Hook"
      - name: robot-gitee-openlookeng-checkpr
        endpoint: http://service-checkpr.robot-gitee-openlookeng.svc.cluster.local:8888/gitee-hook
        events:
        - "Merge Request Hook"
      - name: robot-gitee-openlookeng-lgtm
        endpoint: http://service-lgtm.robot-gitee-openlookeng.svc.cluster.local:8888/gitee-hook
        events:
        - "Merge Request Hook"
        - "Note Hook"
      - name: robot-gitee-openlookeng-associate
        endpoint: http://service-associate.robot-gitee-openlookeng.svc.cluster.local:8888/gitee-hook
        events:
        - "Issue Hook"
        - "Merge Request Hook"
        - "Note Hook"
