apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  config.yaml: |
    access:
      repo_plugins:
        zengchen1024/repo-test:
        - checkpr

      plugins:
      - name: checkpr
        endpoint: http://service-checkpr.robot-gitee.svc.cluster.local:8888/gitee-hook
        events:
        - "Merge Request Hook"
      - name: lifecycle
        endpoint: http://service-lifecycle.robot-gitee.svc.cluster.local:8888/gitee-hook
        events:
        - "Note Hook"
