apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  config.yaml: |
    config_items:
    - repos:
    - xwz123/repo-test
    lgtm_counts_required: 1
    labels_for_merge:
    - openeuler-cla/yes
    unable_checking_reviewer_for_pr: true
    freeze_file:
    - owner: wanghao75
      repo: community
      branch: master
      path: freeze.yaml


    - repos:
    - wanghao75/community
    lgtm_counts_required: 2
    check_permission_based_on_sig_owners: true
    sigs_dir: sig
    labels_for_merge:
    - openeuler-cla/yes
    unable_checking_reviewer_for_pr: true
    freeze_file:
    - owner: wanghao75
      repo: community
      branch: master
      path: freeze.yaml

