apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  config.yaml: |
    access:
      topic: robot-gitee-mindspore
      user_agent: robot-gitee-mindspore
      kafka_address: "${KAFKA_ADDRESS}"
