apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configmap.yaml
- deployment.yaml
- service.yaml
commonLabels:
  component: inference
nameSuffix: -inference
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/xihe
