resources:
- xihe-website.yaml
- namespace.yaml
- secret.yaml
- ingress.yaml
- configmap.yaml
- xihe-server.yaml
- xihe-message-server.yaml
- hook-delivery
- access
namespace: xihe-dev
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/xihe-message-server
  newTag: 9da177fac499b2eb0bba0c52ad51e8fa947be35d
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/xihe-server
  newTag: b6ebbaff5fe0eb92d47527df70e3ea37c1f6b85e
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/xihe-website-test
  newTag: f90f7c98dcd504cc3e0c935f972a11e66547990a
