apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  config.yaml: |
    config_items:
    - repos:
      - opengauss
      cla_label_yes: opengauss-cla/yes
      cla_label_no: opengauss-cla/no
      check_url: https://clasign.osinfra.cn/api/v1/individual-signing/gitee_opengauss-1614047760000855378
      sign_url: https://clasign.osinfra.cn/sign/gitee_opengauss-1614047760000855378
      faq_url: https://gitee.com/opengauss/community/blob/master/cla/faq/check-by-author/faq.md
