apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configmap.yaml
- deployment.yaml
- service.yaml
commonLabels:
  component: hook-dispatcher
nameSuffix: -hook-dispatcher
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/xihe-gitlab
  newName: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/robot-hook-dispatcher
  newTag: main-15cf065
