apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- access
- checkpr
- repo-file-cache
- sync-file-server
- sync-repo-file
- lifecycle
- welcome
commonLabels:
  app: infrastructure-robot-gitee
commonAnnotations:
  email: chenzeng765@163.com
  owner: chenzeng
namespace: robot-gitee
