apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- secrets.yaml
- access
- repo-file-cache
- sync-file-server
- sync-repo-file
- repo-owners-cache
- sync-repo-file-job
- sync-repository-server
- sync-repository-trigger
commonLabels:
  app: infrastructure-robot-gitee
commonAnnotations:
  email: chenzeng765@163.com
  owner: chenzeng
namespace: robot-gitee
