apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  config.yaml: |
    inference: 
      gitlab_endpiont: "${GITLAB_HOST}"
      obs:
        access_key: "${HW_OBS_AK}"
        secret_key: "${HW_OBS_SK}"
        endpoint: "${HW_OBS_ENDPOINT}"
        bucket: "${HW_OBS_BUCKET}"
        obsutil_path: /usr/src/app/obsutil
        lfs_path: gitlab-lfs

    watch:
      inference_endpoint: service-internal-server.xihe-test-v2.svc.cluster.local:8888
