apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  config.yaml: |
    config_items:
    - repos:
      - xwz123/repo-test
      enable_sync_issue: true
      enable_sync_comment: true
      sync_org_mapping:
        xwz123: zengchen1024 