apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
  namespace: xihe-test-v2
data:
  default.conf: |
    map $http_upgrade $connection_upgrade {
      default upgrade;
      '' close;
    }

    server {
      # listen 443 ssl;
      # server_name localhost;
      # charset utf-8;

      listen 8080;
      server_name localhost;
      charset utf-8;
      limit_conn perserver 50;
      if ($request_method = 'OPTIONS') {
        return 401;
      }

      location / {
        location /assets {
          # publish every two weeks
          expires 14d;
          add_header Cache-Control public;
        }
        location / {
          add_header Cache-Control no-cache;
          proxy_set_header Host $host;
          try_files $uri /index.html;
        }

        root /usr/share/nginx/html;
        index /index.html;
        proxy_set_header Host $host;
        #   error_page 404 /404.html;
      }

      location ^~ /server/ {
        proxy_pass http://xihe-backend-service.xihe-test-v2.svc.cluster.local/api/v1/ ;
      }

      location ^~ /repo/ {
        proxy_pass https://gitlab.openeuler.sh/api/v4/ ;
      }

      error_page 500 501 502 503 504 505 /500.html;
      error_page 401 /401.html;
      error_page 404 /404.html;

      location = /401.html {
        root /usr/share/nginx/html;
      }

      location = /404.html {
        root /usr/share/nginx/html;
      }

      location = /500.html {
        root /usr/share/nginx/html;
      }
    }

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: server-configmap
  namespace: xihe-test-v2
data:
  config.yaml: |
    default_password: "${DEFAULT_PASSWORD}"
    authing_service:
      app_id: "${AUTHING_APP_ID}"
      secret: "${AUTHING_SECRET}"
      redirect_uri: "${AUTHING_REDIRECT_URI_TEST}"

    mongodb:
      mongodb_conn: "${MONGODB_CONNECTION}"
      mongodb_db: "${MONGODB_NAME}"
      project_collection: project
      model_collection: model
      dataset_collection: dataset 
      user_collection: user
      login_collection: login
      like_collection: like
      activity_collection: activity

    gitlab:
      endpoint: "${GITLAB_ENDPOINT}"
      root_token: "${GITLAB_TOKEN}"

    api:
      api_token_expiry: 3600
      api_token_key: "${API_TOKEN_KEY}"

    encryption_key: "${ENCRYPTION_KEY}"

    resource:
      covers:
      - "1"
      - "2"
      - "3"
      - "4"

      protocols:
      - "apache 2.0"
      - "mit"

      project_type:
      - "Gradio"
      - "Static"

      training_platform:
      - "ModelArts"

    mq:
      address: "${KAFKA_ADDRESS}"
      topic_like: "xihe_like_test"
      topic_following: "xihe_following_test"
