resources:
- xihe-website.yaml
- namespace.yaml
- secret.yaml
- ingress.yaml
- configmap.yaml
- xihe-server.yaml
- internal-server
- message-server
- hook-delivery
- hook-dispatcher
- access
- sync-repo
- training-center-huaweicloud
namespace: xihe-test-v2
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/xihe-server
  newTag: a2eba9646201094e0286f13c5cede9ae455fd453
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/xihe-website-test
  newTag: 417994c3c3f191d62adbfcf6bd2da2e1c45b3465
