apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  config.yaml: |
    training_endpoint: http://service-training-center-huaweicloud.xihe-new.svc.cluster.local:8888/api/v1/training
    mongodb:
      mongodb_conn: "${MONGODB_CONNECTION}"
      mongodb_db: "${MONGODB_NAME}"
      project_collection: project
      model_collection: model
      dataset_collection: dataset 
      user_collection: user
      login_collection: login
      like_collection: like
      activity_collection: activity
      tag_collection: tag
      training_collection: training
      evaluate_collection: evaluate
      inference_collection: inference

    domain:
      covers:
      - "1"
      - "2"
      - "3"
      - "4"

      protocols:
      - "apache 2.0"
      - "mit"

      project_type:
      - "Gradio"
      - "Static"

      training_platform:
      - "ModelArts"

    mq:
      address: "${KAFKA_ADDRESS}"
      topics:
        fork: "xihe_fork_new"
        like: "xihe_like_new"
        evaluate: "xihe_evaluate_new"
        training: "xihe_training_new"
        inference: "xihe_inference_new"
        following: "xihe_following_new"
        related_resource: "xihe_related_resource_new"

    evaluate:
      endpoint: http://service-inference-evaluate.xihe-new.svc.cluster.local:8888

    inference:
      endpoint: http://service-inference-evaluate.xihe-new.svc.cluster.local:8888
