apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/robot/robot-github
  newName: swr.cn-north-4.myhuaweicloud.com/opensourceway/robot/robot-github-openeuler-repo-watcher
  newTag: main-e99cd8f
