---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: xihe-cluster-secret
  namespace: xihe-new
spec:
  name: xihe-cluster-secret-inference-evaluate
  keysMap:
    cluster_kubeconfig:
      path: secrets/data/mindspore/xihe-new
      key: cluster_kubeconfig
