apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- secrets.yaml
- service.yaml
commonLabels:
  component: sync-file-server
nameSuffix: -sync-file-server
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/robot/robot-gitee
  newName: swr.cn-north-4.myhuaweicloud.com/opensourceway/robot/sync-file-server
  newTag: master-524c9f3
