apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: secret
spec:
  name: secret-hook-delivery
  keysMap:
    systemhook-hmac:
      path: secrets/data/mindspore/xihe-gitlab
      key: systemhook-hmac
    kafka:
      path: secrets/data/mindspore/xihe-gitlab
      key: kafka
