apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: secret-robot-nlp-aksk
spec:
  name: secret-robot-nlp-aksk
  keysMap:
    nlp-ak:
      path: secrets/data/mindspore/robot-gitee
      key: robot-nlp-ak
    nlp-sk:
      path: secrets/data/mindspore/robot-gitee
      key: robot-nlp-sk