apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  config.yaml: |
    training: 
      access_key: "${HW_OBS_AK}"
      secret_key: "${HW_OBS_SK}"
      region: "${HW_MODELARTS_REGION}"
      project_name: "${HW_MODELARTS_PROJECT_NAME}"
      project_id: "${HW_MODELARTS_PROJECT_ID}"
      endpoint: "${HW_MODELARTS_ENDPOINT}"
      obs_bucket: "${HW_OBS_BUCKET}"
      obs_repo_path: xihe-repos

    sync:
      access_key: "${HW_OBS_AK}"
      secret_key: "${HW_OBS_SK}"
      endpoint: "${HW_OBS_ENDPOINT}"
      bucket: "${HW_OBS_BUCKET}"
      work_dir: "/opt/app/sync_repo"
      repo_path: xihe-repos
      commit_file: synced_commit
      obsutil_path: /opt/app/obsutil
      sync_file_shell: /opt/app/sync_file.sh

    mysql:
      conn: "${MYSQL_CONN}"
      conn_max_life_time: 1
      project_table_name: "project"

    gitlab:
      token: "${GITLAB_TOKEN}"
      host: "${GITLAB_HOST}"
