apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  config.yaml: |
    mongodb:
      db_conn: "${MONGODB_CONNECTION}"
      db_name: "${MONGODB_NAME}"
      collections:
        project: project
        model: model
        dataset: dataset 
        user: user
        login: login
        like: like
        activity: activity
        tag: tag
        training: training
        evaluate: evaluate
        inference: inference
        competition: competition

    domain:
      covers:
      - "1"
      - "2"
      - "3"
      - "4"

      protocols:
      - "apache 2.0"
      - "mit"

      project_type:
      - "Gradio"
      - "Static"

      training_platform:
      - "ModelArts"
