apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: internal-server
        image: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/xihe-internal-server:3d4482ebdcc17188b7853f732bc50226f88e8e2c
        imagePullPolicy: IfNotPresent
        args:
        - --port=8888
        - --config-file=/opt/app/conf/config.yaml
        - --enable_debug=true
        env:
        - name: MONGODB_NAME
          valueFrom:
            secretKeyRef:
              name: xihe-secret
              key: MONGODB_NAME
        - name: MONGODB_CONNECTION
          valueFrom:
            secretKeyRef:
              name: xihe-secret
              key: MONGODB_CONNECTION
        resources:
          requests:
            cpu: 1000m
            memory: 1000Mi
          limits:
            cpu: 1000m
            memory: 1000Mi
        ports:
        - containerPort: 8888
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /opt/app/conf
          name: config
      volumes:
      - name: config
        configMap:
          name: configmap-internal-server
