apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  config.yaml: |
    training_endpoint: http://service-training-center-huaweicloud.xihe-test-v2.svc.cluster.local:8888/api/v1/training
    mongodb:
      db_conn: "${MONGODB_CONNECTION}"
      db_name: "${MONGODB_NAME}"
      collections:
        project: project
        model: model
        dataset: dataset 
        user: user
        login: login
        like: like
        activity: activity
        tag: tag
        training: training
        evaluate: evaluate
        inference: inference
        competition: competition

    domain:
      covers:
      - "1"
      - "2"
      - "3"
      - "4"

      protocols:
      - "apache 2.0"
      - "mit"

      project_type:
      - "Gradio"
      - "Static"

      training_platform:
      - "ModelArts"

    mq:
      address: "${KAFKA_ADDRESS}"
      topics:
        fork: "xihe_fork_test"
        like: "xihe_like_test"
        evaluate: "xihe_evaluate_test"
        training: "xihe_training_test"
        inference: "xihe_inference_test"
        following: "xihe_following_test"
        related_resource: "xihe_related_resource_test"

    evaluate:
      endpoint: http://service-inference-evaluate.xihe-test-v2.svc.cluster.local:8888

    inference:
      endpoint: http://service-inference-evaluate.xihe-test-v2.svc.cluster.local:8888
