apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  config.yaml: |
    access:
      repo_plugins:
        mindspore:
        - review-trigger-new
        - tide
        - cla
        - label
        - lifecycle
        - assign

        YwHql/test:
        - test

      plugins:
      - name: cla
        endpoint: http://service-cla.robot-gitee-mindspore.svc.cluster.local:8888/gitee-hook
        events:
        - "Merge Request Hook"
        - "Note Hook"
      - name: label
        endpoint: http://service-label.robot-gitee-mindspore.svc.cluster.local:8888/gitee-hook
        events:
        - "Merge Request Hook"
        - "Note Hook"
      - name: tide
        endpoint: http://service-tide.robot-gitee-mindspore.svc.cluster.local:8888/gitee-hook
        events:
        - "Merge Request Hook"
        - "Note Hook"
      - name: lifecycle
        endpoint: http://service-lifecycle.robot-gitee-mindspore.svc.cluster.local:8888/gitee-hook
        events:
        - "Note Hook"
      - name: assign
        endpoint: http://service-assign.robot-gitee-mindspore.svc.cluster.local:8888/gitee-hook
        events:
        - "Note Hook"
      - name: review-trigger-new
        endpoint: http://service-review-trigger-new.robot-gitee-mindspore.svc.cluster.local:8888/gitee-hook
        events:
        - "Merge Request Hook"
        - "Note Hook"
      - name: test
        endpoint: http://service-test.robot-gitee-mindspore.svc.cluster.local:8888/gitee-hook
        events:
        - "Issue Hook"
        - "Merge Request Hook"
        - "Push Hook"
        - "Note Hook"
