apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  namespace: robot-gitee
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: sync-repository-server
        args:
        - --config-file=/opt/app/config/config.yaml
        image: swr.cn-north-4.myhuaweicloud.com/opensourceway/robot/robot-gitee:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: KAFKA_ADDRESS
            valueFrom:
              secretKeyRef:
                name: robot-gitee-secret
                key: kafka_address
          - name: ROBOT_TOKEN
            valueFrom:
              secretKeyRef:
                name: robot-gitee-secret
                key: robot-token
        volumeMounts:
          - mountPath: /opt/app/config/config.yaml
            name: configmap
            subPath: config.yaml
      volumes:
        - configMap:
            defaultMode: 420
            name: configmap
          name: configmap
        - name: robot-gitee-secret
          secret:
            secretName: robot-gitee-secret

