apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  config.yaml: |
    access:
      broker:
        addresses:
        - 121.36.22.144:9094
        - 124.70.16.28:9094
        - 119.3.250.251:9094
      repo_plugins:
        xwz123/repo-test:
        - robot-github-openlookeng-synchronizer
        - robot-github-openeuler-cla

      plugins:
      - name: robot-github-synchronizer
        endpoint: http://service-synchronizer.robot-github.svc.cluster.local:8888/github-hook
        events:
        - "issues"
        - "issue_comment"
        
      - name: robot-github-openlookeng-synchronizer
        endpoint: http://service-synchronizer.robot-github-openlookeng.svc.cluster.local:8888/github-hook
        events:
        - "issues"
        - "issue_comment"        
       
      - name: robot-github-openeuler-cla
        endpoint: http://service-cla.robot-github-openeuler.svc.cluster.local:8888/github-hook
        events:
        - "pull_request"
        - "issue_comment"
